---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: efk
  namespace: {{ system_namespace }}
subjects:
  - kind: ServiceAccount
    name: efk
    namespace: {{ system_namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
