---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dnsmasq-autoscaler
  namespace: kube-system
  labels:
    k8s-app: dnsmasq-autoscaler
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        k8s-app: dnsmasq-autoscaler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      serviceAccountName: dnsmasq
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
        - name: autoscaler
          image: gcr.io/google_containers/cluster-proportional-autoscaler-amd64:1.1.1
          resources:
            requests:
              cpu: "20m"
              memory: "10Mi"
          command:
            - /cluster-proportional-autoscaler
            - --namespace=kube-system
            - --configmap=dnsmasq-autoscaler
            - --target=Deployment/dnsmasq
            # When cluster is using large nodes(with more cores), "coresPerReplica" should dominate.
            # If using small nodes, "nodesPerReplica" should dominate.
            - --default-params={"linear":{"nodesPerReplica":10,"preventSinglePointFailure":true}}
            - --logtostderr=true
            - --v=2