---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    k8s-app: dnsmasq
  name: dnsmasq
  namespace: kube-system
spec:
  ports:
    - port: 53
      name: dns-tcp
      targetPort: 53
      protocol: TCP
    - port: 53
      name: dns
      targetPort: 53
      protocol: UDP
  type: ClusterIP
  clusterIP: 10.233.0.2
  selector:
    k8s-app: dnsmasq  