---
dependencies:
  - role: kubernetes-apps/network_plugin/calico
    when: kube_network_plugin == 'calico'
    tags:
      - calico

  - role: kubernetes-apps/network_plugin/canal
    when: kube_network_plugin == 'canal'
    tags:
      - canal

  - role: kubernetes-apps/network_plugin/flannel
    when: kube_network_plugin == 'flannel'
    tags:
      - flannel

  - role: kubernetes-apps/network_plugin/weave
    when: kube_network_plugin == 'weave'
    tags:
      - weave
