---
- name: Gen_certs | target ca-certificates path
  set_fact:
    ca_cert_path: |-
      /etc/pki/ca-trust/source/anchors/kube-ca.crt
  tags:
    - facts

- name: Gen_certs | add CA to trusted CA dir
  copy:
    src: "{{ kube_cert_dir }}/ca.pem"
    dest: "{{ ca_cert_path }}"
    remote_src: true
  register: kube_ca_cert

- name: Gen_certs | update ca-certificates (RedHat)
  command: update-ca-trust extract

