---
addusers:
  - name: etcd
    comment: "Etcd user"
    createhome: yes
    home: "{{ etcd_data_dir }}"
    system: yes
    shell: /sbin/nologin

  - name: kube
    comment: "Kubernetes user"
    shell: /sbin/nologin
    system: yes
    group: "{{ kube_cert_group }}"
    createhome: no
