---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-proportional-autoscaler
  namespace: {{ system_namespace }}
subjects:
  - kind: ServiceAccount
    name: cluster-proportional-autoscaler
    namespace: {{ system_namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-proportional-autoscaler
  apiGroup: rbac.authorization.k8s.io
